CodeSystem: HospitalsUris
Id: hospitals-uris
Title: "Hospitals uris"
Description: "CodeSystem of all DGMC Hospitals Uris"
* ^url = $csHospUri
* insert ConformanceMetadata

* #http://fhir.bmc.health.gov.il/identifier/nmr-pat-int-num "ברזילי - מספר מטופל פנימי-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-pat-int-num "נהריה - מספר מטופל פנימי-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-pat-int-num "הלל יפה - מספר מטופל פנימי-נמר"
* #http://fhir.sheba.health.gov.il/identifier/nmr-pat-int-num "שיבא - מספר מטופל פנימי-נמר"
* #http://fhir.b-zion.health.gov.il/identifier/nmr-pat-int-num "בני ציון - מספר מטופל פנימי-נמר"
* #http://fhir.rambam.health.gov.il/identifier/nmr-pat-int-num "רמבם - מספר מטופל פנימי-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-pat-int-num "שמיר - מספר מטופל פנימי-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-pat-int-num "זיו - מספר מטופל פנימי-נמר"
* #http://fhir.Wolfson.health.gov.il/identifier/nmr-pat-int-num "וולפסון - מספר מטופל פנימי-נמר"
* #http://fhir.Tasmc.health.gov.il/identifier/nmr-pat-int-num "איכילוב - מספר מטופל פנימי-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-pat-int-num "פוריה - מספר מטופל פנימי-נמר"

* #http://fhir.bmc.health.gov.il/identifier/nmr-pat-tmp-num "ברזילי - מספר מטופל זמני-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-pat-tmp-num "נהריה - מספר מטופל זמני-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-pat-tmp-num "הלל יפה - מספר מטופל זמני-נמר"
* #http://fhir.sheba.health.gov.il/identifier/nmr-pat-tmp-num "שיבא - מספר מטופל זמני-נמר"
* #http://fhir.b-zion.health.gov.il/identifier/nmr-pat-tmp-num "בני ציון - מספר מטופל זמני-נמר"
* #http://fhir.rambam.health.gov.il/identifier/nmr-pat-tmp-num "רמבם - מספר מטופל זמני-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-pat-tmp-num "שמיר - מספר מטופל זמני-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-pat-tmp-num "זיו - מספר מטופל זמני-נמר"
* #http://fhir.Wolfson.health.gov.il/identifier/nmr-pat-tmp-num "וולפסון - מספר מטופל זמני-נמר"
* #http://fhir.Tasmc.health.gov.il/identifier/nmr-pat-tmp-num "איכילוב - מספר מטופל זמני-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-pat-tmp-num "פוריה - מספר מטופל זמני-נמר"

* #http://fhir.bmc.health.gov.il/identifier/cml-pat-int-num "ברזילי - מספר מטופל פנימי-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-pat-int-num "נהריה - מספר מטופל פנימי-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-pat-int-num "הלל יפה - מספר מטופל פנימי-קמיליון"
* #http://fhir.sheba.health.gov.il/identifier/cml-pat-int-num "שיבא - מספר מטופל פנימי-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-pat-int-num "בני ציון - מספר מטופל פנימי-קמיליון"
* #http://fhir.rambam.health.gov.il/identifier/cml-pat-int-num "רמבם - מספר מטופל פנימי-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-pat-int-num "שמיר - מספר מטופל פנימי-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-pat-int-num "זיו - מספר מטופל פנימי-קמיליון"
* #http://fhir.Wolfson.health.gov.il/identifier/cml-pat-int-num "וולפסון - מספר מטופל פנימי-קמיליון"
* #http://fhir.Tasmc.health.gov.il/identifier/cml-pat-int-num "איכילוב - מספר מטופל פנימי-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-pat-int-num "פוריה - מספר מטופל פנימי-קמיליון"


// ServiceRequest
* #http://fhir.bmc.health.gov.il/identifier/cml-counseling-request "ברזילי - בקשת ייעוץ-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-counseling-request "נהריה - בקשת ייעוץ-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-counseling-request "הלל יפה - בקשת ייעוץ-קמיליון"
* #http://fhir.sheba.health.gov.il/identifier/cml-counseling-request "שיבא - בקשת ייעוץ-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-counseling-request "בני ציון - בקשת ייעוץ-קמיליון"
* #http://fhir.rambam.health.gov.il/identifier/cml-counseling-request "רמבם - בקשת ייעוץ-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-counseling-request "שמיר - בקשת ייעוץ-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-counseling-request "זיו - בקשת ייעוץ-קמיליון"
* #http://fhir.Wolfson.health.gov.il/identifier/cml-counseling-request "וולפסון - בקשת ייעוץ-קמיליון"
* #http://fhir.Tasmc.health.gov.il/identifier/cml-counseling-request "איכילוב - בקשת ייעוץ-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-counseling-request "פוריה - בקשת ייעוץ-קמיליון"


// Procedure
* #http://fhir.bmc.health.gov.il/identifier/cml-counseling-answer "ברזילי - תשובת ייעוץ-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-counseling-answer "נהריה - תשובת ייעוץ-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-counseling-answer "הלל יפה - תשובת ייעוץ-קמיליון"
* #http://fhir.sheba.health.gov.il/identifier/cml-counseling-answer "שיבא - תשובת ייעוץ-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-counseling-answer "בני ציון - תשובת ייעוץ-קמיליון"
* #http://fhir.rambam.health.gov.il/identifier/cml-counseling-answer "רמבם - תשובת ייעוץ-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-counseling-answer "שמיר - תשובת ייעוץ-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-counseling-answer "זיו - תשובת ייעוץ-קמיליון"
* #http://fhir.Wolfson.health.gov.il/identifier/cml-counseling-answer "וולפסון - תשובת ייעוץ-קמיליון"
* #http://fhir.Tasmc.health.gov.il/identifier/cml-counseling-answer "איכילוב - תשובת ייעוץ-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-counseling-answer "פוריה - תשובת ייעוץ-קמיליון"

* #http://fhir.bmc.health.gov.il/identifier/ad-username "ברזילי - שם משתמש של המטפל"
* #http://fhir.gmc.health.gov.il/identifier/ad-username "נהריה - שם משתמש של המטפל"
* #http://fhir.hymc.health.gov.il/identifier/ad-username "הלל יפה - שם משתמש של המטפל"
* #http://fhir.sheba.health.gov.il/identifier/ad-username "שיבא - שם משתמש של המטפל"
* #http://fhir.b-zion.health.gov.il/identifier/ad-username "בני ציון - שם משתמש של המטפל"
* #http://fhir.rambam.health.gov.il/identifier/ad-username "רמבם - שם משתמש של המטפל"
* #http://fhir.shamir.health.gov.il/identifier/ad-username "שמיר - שם משתמש של המטפל"
* #http://fhir.ziv.health.gov.il/identifier/ad-username "זיו - שם משתמש של המטפל"
* #http://fhir.Wolfson.health.gov.il/identifier/ad-username "וולפסון - שם משתמש של המטפל"
* #http://fhir.Tasmc.health.gov.il/identifier/ad-username "איכילוב - שם משתמש של המטפל"
* #http://fhir.tzafon.health.gov.il/identifier/ad-username "פוריה - שם משתמש של המטפל"

* #http://fhir.bmc.health.gov.il/identifier/cml-medical-record "ברזילי - medical record-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-medical-record "נהריה - medical record-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-medical-record "הלל יפה - medical record-קמיליון"
* #http://fhir.sheba.health.gov.il/identifier/cml-medical-record "שיבא - medical record-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-medical-record "בני ציון - medical record-קמיליון"
* #http://fhir.rambam.health.gov.il/identifier/cml-medical-record "רמבם - medical record-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-medical-record "שמיר - medical record-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-medical-record "זיו - medical record-קמיליון"
* #http://fhir.Wolfson.health.gov.il/identifier/cml-medical-record "וולפסון - medical record-קמיליון"
* #http://fhir.Tasmc.health.gov.il/identifier/cml-medical-record "איכילוב - medical record-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-medical-record "פוריה - medical record-קמיליון"

* #http://fhir.bmc.health.gov.il/identifier/cml-user-code "ברזילי - קוד משתמש-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-user-code "נהריה - קוד משתמש-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-user-code "הלל יפה - קוד משתמש-קמיליון"
* #http://fhir.sheba.health.gov.il/identifier/cml-user-code "שיבא - קוד משתמש-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-user-code "בני ציון - קוד משתמש-קמיליון"
* #http://fhir.rambam.health.gov.il/identifier/cml-user-code "רמבם - קוד משתמש-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-user-code "שמיר - קוד משתמש-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-user-code "זיו - קוד משתמש-קמיליון"
* #http://fhir.Wolfson.health.gov.il/identifier/cml-user-code "וולפסון - קוד משתמש-קמיליון"
* #http://fhir.Tasmc.health.gov.il/identifier/cml-user-code "איכילוב - קוד משתמש-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-user-code "פוריה - קוד משתמש-קמיליון"

* #http://fhir.bmc.health.gov.il/identifier/encounter-diet-pref "ברזילי - סוג מזון"
* #http://fhir.gmc.health.gov.il/identifier/encounter-diet-pref "נהריה - סוג מזון"
* #http://fhir.hymc.health.gov.il/identifier/encounter-diet-pref "הלל יפה - סוג מזון"
* #http://fhir.sheba.health.gov.il/identifier/encounter-diet-pref "שיבא - סוג מזון"
* #http://fhir.b-zion.health.gov.il/identifier/encounter-diet-pref "בני ציון - סוג מזון"
* #http://fhir.rambam.health.gov.il/identifier/encounter-diet-pref "רמבם - סוג מזון"
* #http://fhir.shamir.health.gov.il/identifier/encounter-diet-pref "שמיר - סוג מזון"
* #http://fhir.ziv.health.gov.il/identifier/encounter-diet-pref "זיו - סוג מזון"
* #http://fhir.Wolfson.health.gov.il/identifier/encounter-diet-pref "וולפסון - סוג מזון"
* #http://fhir.Tasmc.health.gov.il/identifier/encounter-diet-pref "איכילוב - סוג מזון"
* #http://fhir.tzafon.health.gov.il/identifier/encounter-diet-pref "פוריה - סוג מזון"

* #http://fhir.bmc.health.gov.il/identifier/nmr-case-number "ברזילי - מספר מקרה-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-case-number "נהריה - מספר מקרה-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-case-number "הלל יפה - מספר מקרה-נמר"
* #http://fhir.sheba.health.gov.il/identifier/nmr-case-number "שיבא - מספר מקרה-נמר"
* #http://fhir.b-zion.health.gov.il/identifier/nmr-case-number "בני ציון - מספר מקרה-נמר"
* #http://fhir.rambam.health.gov.il/identifier/nmr-case-number "רמבם - מספר מקרה-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-case-number "שמיר - מספר מקרה-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-case-number "זיו - מספר מקרה-נמר"
* #http://fhir.Wolfson.health.gov.il/identifier/nmr-case-number "וולפסון - מספר מקרה-נמר"
* #http://fhir.Tasmc.health.gov.il/identifier/nmr-case-number "איכילוב - מספר מקרה-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-case-number "פוריה - מספר מקרה-נמר"

* #http://fhir.bmc.health.gov.il/identifier/nmr-movement-number "ברזילי - מספר העברה-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-movement-number "נהריה - מספר העברה-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-movement-number "הלל יפה - מספר העברה-נמר"
* #http://fhir.sheba.health.gov.il/identifier/nmr-movement-number "שיבא - מספר העברה-נמר"
* #http://fhir.b-zion.health.gov.il/identifier/nmr-movement-number "בני ציון - מספר העברה-נמר"
* #http://fhir.rambam.health.gov.il/identifier/nmr-movement-number "רמבם - מספר העברה-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-movement-number "שמיר - מספר העברה-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-movement-number "זיו - מספר העברה-נמר"
* #http://fhir.Wolfson.health.gov.il/identifier/nmr-movement-number "וולפסון - מספר העברה-נמר"
* #http://fhir.Tasmc.health.gov.il/identifier/nmr-movement-number "איכילוב - מספר העברה-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-movement-number "פוריה - מספר העברה-נמר"

* #http://fhir.bmc.health.gov.il/identifier/nmr2cml-identifier "ברזילי -קשר בין תנועת נמר לקמיליון"
* #http://fhir.gmc.health.gov.il/identifier/nmr2cml-identifier "נהריה -קשר בין תנועת נמר לקמיליון"
* #http://fhir.hymc.health.gov.il/identifier/nmr2cml-identifier "הלל יפה -קשר בין תנועת נמר לקמיליון"
* #http://fhir.sheba.health.gov.il/identifier/nmr2cml-identifier "שיבא -קשר בין תנועת נמר לקמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/nmr2cml-identifier "בני ציון -קשר בין תנועת נמר לקמיליון"
* #http://fhir.rambam.health.gov.il/identifier/nmr2cml-identifier "רמבם -קשר בין תנועת נמר לקמיליון"
* #http://fhir.shamir.health.gov.il/identifier/nmr2cml-identifier "שמיר -קשר בין תנועת נמר לקמיליון"
* #http://fhir.ziv.health.gov.il/identifier/nmr2cml-identifier "זיו -קשר בין תנועת נמר לקמיליון"
* #http://fhir.Wolfson.health.gov.il/identifier/nmr2cml-identifier "וולפסון -קשר בין תנועת נמר לקמיליון"
* #http://fhir.Tasmc.health.gov.il/identifier/nmr2cml-identifier "איכילוב -קשר בין תנועת נמר לקמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/nmr2cml-identifier "פוריה -קשר בין תנועת נמר לקמיליון"

* #http://fhir.bmc.health.gov.il/identifier/sap-user-vma "ברזילי -משתמש סאפ"
* #http://fhir.gmc.health.gov.il/identifier/sap-user-vma "נהריה -משתמש סאפ"
* #http://fhir.hymc.health.gov.il/identifier/sap-user-vma "הלל יפה -משתמש סאפ"
* #http://fhir.sheba.health.gov.il/identifier/sap-user-vma "שיבא -משתמש סאפ"
* #http://fhir.b-zion.health.gov.il/identifier/sap-user-vma "בני ציון -משתמש סאפ"
* #http://fhir.rambam.health.gov.il/identifier/sap-user-vma "רמבם -משתמש סאפ"
* #http://fhir.shamir.health.gov.il/identifier/sap-user-vma "שמיר -משתמש סאפ"
* #http://fhir.ziv.health.gov.il/identifier/sap-user-vma "זיו -משתמש סאפ"
* #http://fhir.Wolfson.health.gov.il/identifier/sap-user-vma "וולפסון -משתמש סאפ"
* #http://fhir.Tasmc.health.gov.il/identifier/sap-user-vma "איכילוב -משתמש סאפ"
* #http://fhir.tzafon.health.gov.il/identifier/sap-user-vma "פוריה -משתמש סאפ"


// Organization
* #http://fhir.bmc.health.gov.il/identifier/cml-unit-code "ברזילי - קוד יחידה-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-unit-code "נהריה - קוד יחידה-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-unit-code "הלל יפה - קוד יחידה-קמיליון"
* #http://fhir.sheba.health.gov.il/identifier/cml-unit-code "שיבא - קוד יחידה-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-unit-code "בני ציון - קוד יחידה-קמיליון"
* #http://fhir.rambam.health.gov.il/identifier/cml-unit-code "רמבם - קוד יחידה-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-unit-code "שמיר - קוד יחידה-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-unit-code "זיו - קוד יחידה-קמיליון"
* #http://fhir.Wolfson.health.gov.il/identifier/cml-unit-code "וולפסון - קוד יחידה-קמיליון"
* #http://fhir.Tasmc.health.gov.il/identifier/cml-unit-code "איכילוב - קוד יחידה-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-unit-code "פוריה - קוד יחידה-קמיליון"

* #http://fhir.bmc.health.gov.il/identifier/nmr-orgid-text "ברזילי - מזהה יחידה טקסט-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-orgid-text "נהריה - מזהה יחידה טקסט-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-orgid-text "הלל יפה - מזהה יחידה טקסט-נמר"
* #http://fhir.sheba.health.gov.il/identifier/nmr-orgid-text "שיבא - מזהה יחידה טקסט-נמר"
* #http://fhir.b-zion.health.gov.il/identifier/nmr-orgid-text "בני ציון - מזהה יחידה טקסט-נמר"
* #http://fhir.rambam.health.gov.il/identifier/nmr-orgid-text "רמבם - מזהה יחידה טקסט-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-orgid-text "שמיר - מזהה יחידה טקסט-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-orgid-text "זיו - מזהה יחידה טקסט-נמר"
* #http://fhir.Wolfson.health.gov.il/identifier/nmr-orgid-text "וולפסון - מזהה יחידה טקסט-נמר"
* #http://fhir.Tasmc.health.gov.il/identifier/nmr-orgid-text "איכילוב -מזהה יחידה טקסט-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-orgid-text "פוריה - מזהה יחידה טקסט-נמר"

* #http://fhir.bmc.health.gov.il/identifier/nmr-orgid-code "ברזילי - מזהה יחידה קוד-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-orgid-code "נהריה - מזהה יחידה קוד-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-orgid-code "הלל יפה - מזהה יחידה קוד-נמר"
* #http://fhir.sheba.health.gov.il/identifier/nmr-orgid-code "שיבא - מזהה יחידה קוד-נמר"
* #http://fhir.b-zion.health.gov.il/identifier/nmr-orgid-code "בני ציון - מזהה יחידה קוד-נמר"
* #http://fhir.rambam.health.gov.il/identifier/nmr-orgid-code "רמבם - מזהה יחידה קוד-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-orgid-code "שמיר - מזהה יחידה קוד-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-orgid-code "זיו - מזהה יחידה קוד-נמר"
* #http://fhir.Wolfson.health.gov.il/identifier/nmr-orgid-code "וולפסון - מזהה יחידה קוד-נמר"
* #http://fhir.Tasmc.health.gov.il/identifier/nmr-orgid-code "איכילוב -מזהה יחידה קוד-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-orgid-code "פוריה - מזהה יחידה קוד-נמר"

* #http://fhir.bmc.health.gov.il/identifier/cml-hosp-code "ברזילי - קוד ביח-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-hosp-code "נהריה - קוד ביח-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-hosp-code "הלל יפה - קוד ביח-קמיליון"
* #http://fhir.sheba.health.gov.il/identifier/cml-hosp-code "שיבא - קוד ביח-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-hosp-code "בני ציון - קוד ביח-קמיליון"
* #http://fhir.rambam.health.gov.il/identifier/cml-hosp-code "רמבם - קוד ביח-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-hosp-code "שמיר - קוד ביח-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-hosp-code "זיו - קוד ביח-קמיליון"
* #http://fhir.Wolfson.health.gov.il/identifier/cml-hosp-code "וולפסון - קוד ביח-קמיליון"
* #http://fhir.Tasmc.health.gov.il/identifier/cml-hosp-code "איכילוב - קוד ביח-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-hosp-code "פוריה - קוד ביח-קמיליון"


// Location
* #http://fhir.bmc.health.gov.il/identifier/cml-bed-id "ברזילי - מזהה מיטה-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-bed-id "נהריה - מזהה מיטה-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-bed-id "הלל יפה - מזהה מיטה-קמיליון"
* #http://fhir.sheba.health.gov.il/identifier/cml-bed-id "שיבא - מזהה מיטה-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-bed-id "בני ציון - מזהה מיטה-קמיליון"
* #http://fhir.rambam.health.gov.il/identifier/cml-bed-id "רמבם - מזהה מיטה-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-bed-id "שמיר - מזהה מיטה-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-bed-id "זיו - מזהה מיטה-קמיליון"
* #http://fhir.Wolfson.health.gov.il/identifier/cml-bed-id "וולפסון - מזהה מיטה-קמיליון"
* #http://fhir.Tasmc.health.gov.il/identifier/cml-bed-id "איכילוב - מזהה מיטה-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-bed-id "פוריה - מזהה מיטה-קמיליון"

* #http://fhir.bmc.health.gov.il/identifier/cml-room-id "ברזילי - מזהה חדר-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-room-id "נהריה - מזהה חדר-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-room-id "הלל יפה - מזהה חדר-קמיליון"
* #http://fhir.sheba.health.gov.il/identifier/cml-room-id "שיבא - מזהה חדר-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-room-id "בני ציון - מזהה חדר-קמיליון"
* #http://fhir.rambam.health.gov.il/identifier/cml-room-id "רמבם - מזהה חדר-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-room-id "שמיר - מזהה חדר-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-room-id "זיו - מזהה חדר-קמיליון"
* #http://fhir.Wolfson.health.gov.il/identifier/cml-room-id "וולפסון - מזהה חדר-קמיליון"
* #http://fhir.Tasmc.health.gov.il/identifier/cml-room-id "איכילוב - מזהה חדר-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-room-id "פוריה - מזהה חדר-קמיליון"



