CodeSystem: HospitalsUris
Id: hospitals-uris
Title: "Hospitals uris"
Description: "CodeSystem of all DGMC Hospitals Uris"
* ^url = $csHospUri
* ^caseSensitive = true
// * insert ConformanceMetadata

* #http://fhir.bmc.health.gov.il/identifier/nmr-pat-int-num "ברזילי - מספר מטופל פנימי-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-pat-int-num "נהריה - מספר מטופל פנימי-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-pat-int-num "הלל יפה - מספר מטופל פנימי-נמר"
//* #http://fhir.sheba.health.gov.il/identifier/nmr-pat-int-num "שיבא - מספר מטופל פנימי-נמר"
* #http://fhir.b-zion.health.gov.il/identifier/nmr-pat-int-num "בני ציון - מספר מטופל פנימי-נמר"
//* #http://fhir.rambam.health.gov.il/identifier/nmr-pat-int-num "רמבם - מספר מטופל פנימי-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-pat-int-num "שמיר - מספר מטופל פנימי-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-pat-int-num "זיו - מספר מטופל פנימי-נמר"
* #http://fhir.wolfson.health.gov.il/identifier/nmr-pat-int-num "וולפסון - מספר מטופל פנימי-נמר"
* #http://fhir.tasmc.health.gov.il/identifier/nmr-pat-int-num "איכילוב - מספר מטופל פנימי-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-pat-int-num "פוריה - מספר מטופל פנימי-נמר"

* #http://fhir.bmc.health.gov.il/identifier/nmr-pat-tmp-num "ברזילי - מספר מטופל זמני-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-pat-tmp-num "נהריה - מספר מטופל זמני-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-pat-tmp-num "הלל יפה - מספר מטופל זמני-נמר"
//* #http://fhir.sheba.health.gov.il/identifier/nmr-pat-tmp-num "שיבא - מספר מטופל זמני-נמר"
* #http://fhir.b-zion.health.gov.il/identifier/nmr-pat-tmp-num "בני ציון - מספר מטופל זמני-נמר"
//* #http://fhir.rambam.health.gov.il/identifier/nmr-pat-tmp-num "רמבם - מספר מטופל זמני-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-pat-tmp-num "שמיר - מספר מטופל זמני-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-pat-tmp-num "זיו - מספר מטופל זמני-נמר"
* #http://fhir.wolfson.health.gov.il/identifier/nmr-pat-tmp-num "וולפסון - מספר מטופל זמני-נמר"
* #http://fhir.tasmc.health.gov.il/identifier/nmr-pat-tmp-num "איכילוב - מספר מטופל זמני-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-pat-tmp-num "פוריה - מספר מטופל זמני-נמר"

* #http://fhir.bmc.health.gov.il/identifier/cml-pat-int-num "ברזילי - מספר מטופל פנימי-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-pat-int-num "נהריה - מספר מטופל פנימי-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-pat-int-num "הלל יפה - מספר מטופל פנימי-קמיליון"
//* #http://fhir.sheba.health.gov.il/identifier/cml-pat-int-num "שיבא - מספר מטופל פנימי-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-pat-int-num "בני ציון - מספר מטופל פנימי-קמיליון"
//* #http://fhir.rambam.health.gov.il/identifier/cml-pat-int-num "רמבם - מספר מטופל פנימי-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-pat-int-num "שמיר - מספר מטופל פנימי-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-pat-int-num "זיו - מספר מטופל פנימי-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-pat-int-num "וולפסון - מספר מטופל פנימי-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-pat-int-num "איכילוב - מספר מטופל פנימי-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-pat-int-num "פוריה - מספר מטופל פנימי-קמיליון"


// ServiceRequest
* #http://fhir.bmc.health.gov.il/identifier/cml-counseling-request "ברזילי - בקשת ייעוץ-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-counseling-request "נהריה - בקשת ייעוץ-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-counseling-request "הלל יפה - בקשת ייעוץ-קמיליון"
//* #http://fhir.sheba.health.gov.il/identifier/cml-counseling-request "שיבא - בקשת ייעוץ-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-counseling-request "בני ציון - בקשת ייעוץ-קמיליון"
//* #http://fhir.rambam.health.gov.il/identifier/cml-counseling-request "רמבם - בקשת ייעוץ-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-counseling-request "שמיר - בקשת ייעוץ-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-counseling-request "זיו - בקשת ייעוץ-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-counseling-request "וולפסון - בקשת ייעוץ-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-counseling-request "איכילוב - בקשת ייעוץ-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-counseling-request "פוריה - בקשת ייעוץ-קמיליון"


// Procedure
* #http://fhir.bmc.health.gov.il/identifier/cml-counseling-answer "ברזילי - תשובת ייעוץ-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-counseling-answer "נהריה - תשובת ייעוץ-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-counseling-answer "הלל יפה - תשובת ייעוץ-קמיליון"
//* #http://fhir.sheba.health.gov.il/identifier/cml-counseling-answer "שיבא - תשובת ייעוץ-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-counseling-answer "בני ציון - תשובת ייעוץ-קמיליון"
//* #http://fhir.rambam.health.gov.il/identifier/cml-counseling-answer "רמבם - תשובת ייעוץ-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-counseling-answer "שמיר - תשובת ייעוץ-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-counseling-answer "זיו - תשובת ייעוץ-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-counseling-answer "וולפסון - תשובת ייעוץ-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-counseling-answer "איכילוב - תשובת ייעוץ-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-counseling-answer "פוריה - תשובת ייעוץ-קמיליון"

* #http://fhir.bmc.health.gov.il/identifier/ad-username "ברזילי - שם משתמש של המטפל"
* #http://fhir.gmc.health.gov.il/identifier/ad-username "נהריה - שם משתמש של המטפל"
* #http://fhir.hymc.health.gov.il/identifier/ad-username "הלל יפה - שם משתמש של המטפל"
//* #http://fhir.sheba.health.gov.il/identifier/ad-username "שיבא - שם משתמש של המטפל"
* #http://fhir.b-zion.health.gov.il/identifier/ad-username "בני ציון - שם משתמש של המטפל"
//* #http://fhir.rambam.health.gov.il/identifier/ad-username "רמבם - שם משתמש של המטפל"
* #http://fhir.shamir.health.gov.il/identifier/ad-username "שמיר - שם משתמש של המטפל"
* #http://fhir.ziv.health.gov.il/identifier/ad-username "זיו - שם משתמש של המטפל"
* #http://fhir.wolfson.health.gov.il/identifier/ad-username "וולפסון - שם משתמש של המטפל"
* #http://fhir.tasmc.health.gov.il/identifier/ad-username "איכילוב - שם משתמש של המטפל"
* #http://fhir.tzafon.health.gov.il/identifier/ad-username "פוריה - שם משתמש של המטפל"

* #http://fhir.bmc.health.gov.il/identifier/cml-medical-record "ברזילי - medical record-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-medical-record "נהריה - medical record-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-medical-record "הלל יפה - medical record-קמיליון"
//* #http://fhir.sheba.health.gov.il/identifier/cml-medical-record "שיבא - medical record-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-medical-record "בני ציון - medical record-קמיליון"
//* #http://fhir.rambam.health.gov.il/identifier/cml-medical-record "רמבם - medical record-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-medical-record "שמיר - medical record-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-medical-record "זיו - medical record-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-medical-record "וולפסון - medical record-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-medical-record "איכילוב - medical record-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-medical-record "פוריה - medical record-קמיליון"

* #http://fhir.bmc.health.gov.il/identifier/cml-user-code "ברזילי - קוד משתמש-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-user-code "נהריה - קוד משתמש-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-user-code "הלל יפה - קוד משתמש-קמיליון"
//* #http://fhir.sheba.health.gov.il/identifier/cml-user-code "שיבא - קוד משתמש-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-user-code "בני ציון - קוד משתמש-קמיליון"
//* #http://fhir.rambam.health.gov.il/identifier/cml-user-code "רמבם - קוד משתמש-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-user-code "שמיר - קוד משתמש-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-user-code "זיו - קוד משתמש-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-user-code "וולפסון - קוד משתמש-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-user-code "איכילוב - קוד משתמש-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-user-code "פוריה - קוד משתמש-קמיליון"

* #http://fhir.bmc.health.gov.il/identifier/encounter-diet-pref "ברזילי - סוג מזון"
* #http://fhir.gmc.health.gov.il/identifier/encounter-diet-pref "נהריה - סוג מזון"
* #http://fhir.hymc.health.gov.il/identifier/encounter-diet-pref "הלל יפה - סוג מזון"
//* #http://fhir.sheba.health.gov.il/identifier/encounter-diet-pref "שיבא - סוג מזון"
* #http://fhir.b-zion.health.gov.il/identifier/encounter-diet-pref "בני ציון - סוג מזון"
//* #http://fhir.rambam.health.gov.il/identifier/encounter-diet-pref "רמבם - סוג מזון"
* #http://fhir.shamir.health.gov.il/identifier/encounter-diet-pref "שמיר - סוג מזון"
* #http://fhir.ziv.health.gov.il/identifier/encounter-diet-pref "זיו - סוג מזון"
* #http://fhir.wolfson.health.gov.il/identifier/encounter-diet-pref "וולפסון - סוג מזון"
* #http://fhir.tasmc.health.gov.il/identifier/encounter-diet-pref "איכילוב - סוג מזון"
* #http://fhir.tzafon.health.gov.il/identifier/encounter-diet-pref "פוריה - סוג מזון"

* #http://fhir.bmc.health.gov.il/identifier/nmr-case-number "ברזילי - מספר מקרה-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-case-number "נהריה - מספר מקרה-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-case-number "הלל יפה - מספר מקרה-נמר"
//* #http://fhir.sheba.health.gov.il/identifier/nmr-case-number "שיבא - מספר מקרה-נמר"
* #http://fhir.b-zion.health.gov.il/identifier/nmr-case-number "בני ציון - מספר מקרה-נמר"
//* #http://fhir.rambam.health.gov.il/identifier/nmr-case-number "רמבם - מספר מקרה-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-case-number "שמיר - מספר מקרה-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-case-number "זיו - מספר מקרה-נמר"
* #http://fhir.wolfson.health.gov.il/identifier/nmr-case-number "וולפסון - מספר מקרה-נמר"
* #http://fhir.tasmc.health.gov.il/identifier/nmr-case-number "איכילוב - מספר מקרה-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-case-number "פוריה - מספר מקרה-נמר"

* #http://fhir.bmc.health.gov.il/identifier/nmr-movement-number "ברזילי - מספר העברה-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-movement-number "נהריה - מספר העברה-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-movement-number "הלל יפה - מספר העברה-נמר"
//* #http://fhir.sheba.health.gov.il/identifier/nmr-movement-number "שיבא - מספר העברה-נמר"
* #http://fhir.b-zion.health.gov.il/identifier/nmr-movement-number "בני ציון - מספר העברה-נמר"
//* #http://fhir.rambam.health.gov.il/identifier/nmr-movement-number "רמבם - מספר העברה-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-movement-number "שמיר - מספר העברה-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-movement-number "זיו - מספר העברה-נמר"
* #http://fhir.wolfson.health.gov.il/identifier/nmr-movement-number "וולפסון - מספר העברה-נמר"
* #http://fhir.tasmc.health.gov.il/identifier/nmr-movement-number "איכילוב - מספר העברה-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-movement-number "פוריה - מספר העברה-נמר"

* #http://fhir.bmc.health.gov.il/identifier/nmr2cml-identifier "ברזילי - קשר בין תנועת נמר לקמיליון"
* #http://fhir.gmc.health.gov.il/identifier/nmr2cml-identifier "נהריה - קשר בין תנועת נמר לקמיליון"
* #http://fhir.hymc.health.gov.il/identifier/nmr2cml-identifier "הלל יפה - קשר בין תנועת נמר לקמיליון"
//* #http://fhir.sheba.health.gov.il/identifier/nmr2cml-identifier "שיבא - קשר בין תנועת נמר לקמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/nmr2cml-identifier "בני ציון - קשר בין תנועת נמר לקמיליון"
//* #http://fhir.rambam.health.gov.il/identifier/nmr2cml-identifier "רמבם - קשר בין תנועת נמר לקמיליון"
* #http://fhir.shamir.health.gov.il/identifier/nmr2cml-identifier "שמיר - קשר בין תנועת נמר לקמיליון"
* #http://fhir.ziv.health.gov.il/identifier/nmr2cml-identifier "זיו - קשר בין תנועת נמר לקמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/nmr2cml-identifier "וולפסון - קשר בין תנועת נמר לקמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/nmr2cml-identifier "איכילוב - קשר בין תנועת נמר לקמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/nmr2cml-identifier "פוריה - קשר בין תנועת נמר לקמיליון"


* #http://fhir.bmc.health.gov.il/identifier/sap-user-vma "ברזילי - משתמש סאפ"
* #http://fhir.gmc.health.gov.il/identifier/sap-user-vma "נהריה - משתמש סאפ"
* #http://fhir.hymc.health.gov.il/identifier/sap-user-vma "הלל יפה - משתמש סאפ"
//* #http://fhir.sheba.health.gov.il/identifier/sap-user-vma "שיבא - משתמש סאפ"
* #http://fhir.b-zion.health.gov.il/identifier/sap-user-vma "בני ציון - משתמש סאפ"
//* #http://fhir.rambam.health.gov.il/identifier/sap-user-vma "רמבם - משתמש סאפ"
* #http://fhir.shamir.health.gov.il/identifier/sap-user-vma "שמיר - משתמש סאפ"
* #http://fhir.ziv.health.gov.il/identifier/sap-user-vma "זיו - משתמש סאפ"
* #http://fhir.wolfson.health.gov.il/identifier/sap-user-vma "וולפסון - משתמש סאפ"
* #http://fhir.tasmc.health.gov.il/identifier/sap-user-vma "איכילוב - משתמש סאפ"
* #http://fhir.tzafon.health.gov.il/identifier/sap-user-vma "פוריה - משתמש סאפ"


// Organization
* #http://fhir.bmc.health.gov.il/identifier/cml-ou-code "ברזילי - קוד יחידה-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-ou-code "נהריה - קוד יחידה-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-ou-code "הלל יפה - קוד יחידה-קמיליון"
//* #http://fhir.sheba.health.gov.il/identifier/cml-ou-code "שיבא - קוד יחידה-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-ou-code "בני ציון - קוד יחידה-קמיליון"
//* #http://fhir.rambam.health.gov.il/identifier/cml-ou-code "רמבם - קוד יחידה-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-ou-code "שמיר - קוד יחידה-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-ou-code "זיו - קוד יחידה-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-ou-code "וולפסון - קוד יחידה-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-ou-code "איכילוב - קוד יחידה-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-ou-code "פוריה - קוד יחידה-קמיליון"

* #http://fhir.bmc.health.gov.il/identifier/nmr-ou-text "ברזילי - מזהה יחידה טקסט-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-ou-text "נהריה - מזהה יחידה טקסט-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-ou-text "הלל יפה - מזהה יחידה טקסט-נמר"
//* #http://fhir.sheba.health.gov.il/identifier/nmr-ou-text "שיבא - מזהה יחידה טקסט-נמר"
* #http://fhir.b-zion.health.gov.il/identifier/nmr-ou-text "בני ציון - מזהה יחידה טקסט-נמר"
//* #http://fhir.rambam.health.gov.il/identifier/nmr-ou-text "רמבם - מזהה יחידה טקסט-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-ou-text "שמיר - מזהה יחידה טקסט-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-ou-text "זיו - מזהה יחידה טקסט-נמר"
* #http://fhir.wolfson.health.gov.il/identifier/nmr-ou-text "וולפסון - מזהה יחידה טקסט-נמר"
* #http://fhir.tasmc.health.gov.il/identifier/nmr-ou-text "איכילוב -מזהה יחידה טקסט-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-ou-text "פוריה - מזהה יחידה טקסט-נמר"

* #http://fhir.bmc.health.gov.il/identifier/nmr-ou-code "ברזילי - מזהה יחידה קוד-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-ou-code "נהריה - מזהה יחידה קוד-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-ou-code "הלל יפה - מזהה יחידה קוד-נמר"
//* #http://fhir.sheba.health.gov.il/identifier/nmr-ou-code "שיבא - מזהה יחידה קוד-נמר"
* #http://fhir.b-zion.health.gov.il/identifier/nmr-ou-code "בני ציון - מזהה יחידה קוד-נמר"
//* #http://fhir.rambam.health.gov.il/identifier/nmr-ou-code "רמבם - מזהה יחידה קוד-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-ou-code "שמיר - מזהה יחידה קוד-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-ou-code "זיו - מזהה יחידה קוד-נמר"
* #http://fhir.wolfson.health.gov.il/identifier/nmr-ou-code "וולפסון - מזהה יחידה קוד-נמר"
* #http://fhir.tasmc.health.gov.il/identifier/nmr-ou-code "איכילוב -מזהה יחידה קוד-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-ou-code "פוריה - מזהה יחידה קוד-נמר"

* #http://fhir.bmc.health.gov.il/identifier/cml-hosp-code "ברזילי - קוד ביח-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-hosp-code "נהריה - קוד ביח-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-hosp-code "הלל יפה - קוד ביח-קמיליון"
//* #http://fhir.sheba.health.gov.il/identifier/cml-hosp-code "שיבא - קוד ביח-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-hosp-code "בני ציון - קוד ביח-קמיליון"
//* #http://fhir.rambam.health.gov.il/identifier/cml-hosp-code "רמבם - קוד ביח-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-hosp-code "שמיר - קוד ביח-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-hosp-code "זיו - קוד ביח-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-hosp-code "וולפסון - קוד ביח-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-hosp-code "איכילוב - קוד ביח-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-hosp-code "פוריה - קוד ביח-קמיליון"


// Location
* #http://fhir.bmc.health.gov.il/identifier/cml-bed-id "ברזילי - מזהה מיטה-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-bed-id "נהריה - מזהה מיטה-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-bed-id "הלל יפה - מזהה מיטה-קמיליון"
//* #http://fhir.sheba.health.gov.il/identifier/cml-bed-id "שיבא - מזהה מיטה-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-bed-id "בני ציון - מזהה מיטה-קמיליון"
//* #http://fhir.rambam.health.gov.il/identifier/cml-bed-id "רמבם - מזהה מיטה-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-bed-id "שמיר - מזהה מיטה-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-bed-id "זיו - מזהה מיטה-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-bed-id "וולפסון - מזהה מיטה-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-bed-id "איכילוב - מזהה מיטה-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-bed-id "פוריה - מזהה מיטה-קמיליון"

* #http://fhir.bmc.health.gov.il/identifier/cml-room-id "ברזילי - מזהה חדר-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-room-id "נהריה - מזהה חדר-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-room-id "הלל יפה - מזהה חדר-קמיליון"
//* #http://fhir.sheba.health.gov.il/identifier/cml-room-id "שיבא - מזהה חדר-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-room-id "בני ציון - מזהה חדר-קמיליון"
//* #http://fhir.rambam.health.gov.il/identifier/cml-room-id "רמבם - מזהה חדר-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-room-id "שמיר - מזהה חדר-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-room-id "זיו - מזהה חדר-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-room-id "וולפסון - מזהה חדר-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-room-id "איכילוב - מזהה חדר-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-room-id "פוריה - מזהה חדר-קמיליון"


// AllergyIntolerance
* #http://fhir.bmc.health.gov.il/identifier/allergyInt-other "ברזילי - מזהה רגישות - אחר"
* #http://fhir.gmc.health.gov.il/identifier/allergyInt-other "נהריה - מזהה רגישות - אחר"
* #http://fhir.hymc.health.gov.il/identifier/allergyInt-other "הלל יפה - מזהה רגישות - אחר"
//* #http://fhir.sheba.health.gov.il/identifier/allergyInt-other "שיבא - מזהה רגישות - אחר"
* #http://fhir.b-zion.health.gov.il/identifier/allergyInt-other "בני ציון - מזהה רגישות - אחר"
//* #http://fhir.rambam.health.gov.il/identifier/allergyInt-other "רמבם - מזהה רגישות - אחר"
* #http://fhir.shamir.health.gov.il/identifier/allergyInt-other "שמיר - מזהה רגישות - אחר"
* #http://fhir.ziv.health.gov.il/identifier/allergyInt-other "זיו - מזהה רגישות - אחר"
* #http://fhir.wolfson.health.gov.il/identifier/allergyInt-other "וולפסון - מזהה רגישות - אחר"
* #http://fhir.tasmc.health.gov.il/identifier/allergyInt-other "איכילוב - מזהה רגישות - אחר"
* #http://fhir.tzafon.health.gov.il/identifier/allergyInt-other "פוריה - מזהה רגישות - אחר"

* #http://fhir.bmc.health.gov.il/identifier/allergyInt-comment "ברזילי - מזהה רגישות - הערה"
* #http://fhir.gmc.health.gov.il/identifier/allergyInt-comment "נהריה - מזהה רגישות - הערה"
* #http://fhir.hymc.health.gov.il/identifier/allergyInt-comment "הלל יפה - מזהה רגישות - הערה"
//* #http://fhir.sheba.health.gov.il/identifier/allergyInt-comment "שיבא - מזהה רגישות - הערה"
* #http://fhir.b-zion.health.gov.il/identifier/allergyInt-comment "בני ציון - מזהה רגישות - הערה"
//* #http://fhir.rambam.health.gov.il/identifier/allergyInt-comment "רמבם - מזהה רגישות - הערה"
* #http://fhir.shamir.health.gov.il/identifier/allergyInt-comment "שמיר - מזהה רגישות - הערה"
* #http://fhir.ziv.health.gov.il/identifier/allergyInt-comment "זיו - מזהה רגישות - הערה"
* #http://fhir.wolfson.health.gov.il/identifier/allergyInt-comment "וולפסון - מזהה רגישות - הערה"
* #http://fhir.tasmc.health.gov.il/identifier/allergyInt-comment "איכילוב - מזהה רגישות - הערה"
* #http://fhir.tzafon.health.gov.il/identifier/allergyInt-comment "פוריה - מזהה רגישות - הערה"

* #http://fhir.bmc.health.gov.il/identifier/allergyInt-medication "ברזילי - מזהה רגישות - תרופות"
* #http://fhir.gmc.health.gov.il/identifier/allergyInt-medication "נהריה - מזהה רגישות - תרופות"
* #http://fhir.hymc.health.gov.il/identifier/allergyInt-medication "הלל יפה - מזהה רגישות - תרופות"
//* #http://fhir.sheba.health.gov.il/identifier/allergyInt-medication "שיבא - מזהה רגישות - תרופות"
* #http://fhir.b-zion.health.gov.il/identifier/allergyInt-medication "בני ציון - מזהה רגישות - תרופות"
//* #http://fhir.rambam.health.gov.il/identifier/allergyInt-medication "רמבם - מזהה רגישות - תרופות"
* #http://fhir.shamir.health.gov.il/identifier/allergyInt-medication "שמיר - מזהה רגישות - תרופות"
* #http://fhir.ziv.health.gov.il/identifier/allergyInt-medication "זיו - מזהה רגישות - תרופות"
* #http://fhir.wolfson.health.gov.il/identifier/allergyInt-medication "וולפסון - מזהה רגישות - תרופות"
* #http://fhir.tasmc.health.gov.il/identifier/allergyInt-medication "איכילוב - מזהה רגישות - תרופות"
* #http://fhir.tzafon.health.gov.il/identifier/allergyInt-medication "פוריה - מזהה רגישות - תרופות"

* #http://fhir.bmc.health.gov.il/cs/allergyInt-code-other "ברזילי - קודי רגישות - אחר"
* #http://fhir.gmc.health.gov.il/cs/allergyInt-code-other "נהריה - קודי רגישות - אחר"
* #http://fhir.hymc.health.gov.il/cs/allergyInt-code-other "הלל יפה - קודי רגישות - אחר"
//* #http://fhir.sheba.health.gov.il/cs/allergyInt-code-other "שיבא - קודי רגישות - אחר"
* #http://fhir.b-zion.health.gov.il/cs/allergyInt-code-other "בני ציון - קודי רגישות - אחר"
//* #http://fhir.rambam.health.gov.il/cs/allergyInt-code-other "רמבם - קודי רגישות - אחר"
* #http://fhir.shamir.health.gov.il/cs/allergyInt-code-other "שמיר - קודי רגישות - אחר"
* #http://fhir.ziv.health.gov.il/cs/allergyInt-code-other "זיו - קודי רגישות - אחר אחר"
* #http://fhir.wolfson.health.gov.il/cs/allergyInt-code-other "וולפסון - קודי רגישות - אחר"
* #http://fhir.tasmc.health.gov.il/cs/allergyInt-code-other "איכילוב - קודי רגישות - אחר"
* #http://fhir.tzafon.health.gov.il/cs/allergyInt-code-other "פוריה - קודי רגישות - אחר"

* #http://fhir.bmc.health.gov.il/cs/allergyInt-code-external "ברזילי - קודי רגישות - קוד חיצוני"
* #http://fhir.gmc.health.gov.il/cs/allergyInt-code-external "נהריה - קודי רגישות - קוד חיצוני"
* #http://fhir.hymc.health.gov.il/cs/allergyInt-code-external "הלל יפה - קודי רגישות - קוד חיצוני"
//* #http://fhir.sheba.health.gov.il/cs/allergyInt-code-external "שיבא - קודי רגישות - קוד חיצוני"
* #http://fhir.b-zion.health.gov.il/cs/allergyInt-code-external "בני ציון - קודי רגישות - קוד חיצוני"
//* #http://fhir.rambam.health.gov.il/cs/allergyInt-code-external "רמבם - קודי רגישות - קוד חיצוני"
* #http://fhir.shamir.health.gov.il/cs/allergyInt-code-external "שמיר - קודי רגישות - קוד חיצוני"
* #http://fhir.ziv.health.gov.il/cs/allergyInt-code-external "זיו - קודי רגישות - קוד חיצוני"
* #http://fhir.wolfson.health.gov.il/cs/allergyInt-code-external "וולפסון - קודי רגישות - קוד חיצוני"
* #http://fhir.tasmc.health.gov.il/cs/allergyInt-code-external "איכילוב - קודי רגישות - קוד חיצוני"
* #http://fhir.tzafon.health.gov.il/cs/allergyInt-code-external "פוריה - קודי רגישות - קוד חיצוני"

* #http://fhir.bmc.health.gov.il/cs/allergyInt-code-medication "ברזילי - קודי רגישות - תרופות"
* #http://fhir.gmc.health.gov.il/cs/allergyInt-code-medication "נהריה - קודי רגישות - תרופות"
* #http://fhir.hymc.health.gov.il/cs/allergyInt-code-medication "הלל יפה - קודי רגישות - תרופות"
//* #http://fhir.sheba.health.gov.il/cs/allergyInt-code-medication "שיבא - קודי רגישות - תרופות"
* #http://fhir.b-zion.health.gov.il/cs/allergyInt-code-medication "בני ציון - קודי רגישות - תרופות"
//* #http://fhir.rambam.health.gov.il/cs/allergyInt-code-medication "רמבם - קודי רגישות - תרופות"
* #http://fhir.shamir.health.gov.il/cs/allergyInt-code-medication "שמיר - קודי רגישות - תרופות"
* #http://fhir.ziv.health.gov.il/cs/allergyInt-code-medication "זיו - קודי רגישות - תרופות"
* #http://fhir.wolfson.health.gov.il/cs/allergyInt-code-medication "וולפסון - קודי רגישות - תרופות"
* #http://fhir.tasmc.health.gov.il/cs/allergyInt-code-medication "איכילוב - קודי רגישות - תרופות"
* #http://fhir.tzafon.health.gov.il/cs/allergyInt-code-medication "פוריה - קודי רגישות - תרופות"

* #http://fhir.bmc.health.gov.il/cs/allergyInt-reaction "ברזילי - קודי תגובה לרגישות"
* #http://fhir.gmc.health.gov.il/cs/allergyInt-reaction "נהריה - קודי תגובה לרגישות"
* #http://fhir.hymc.health.gov.il/cs/allergyInt-reaction "הלל יפה - קודי תגובה לרגישות"
//* #http://fhir.sheba.health.gov.il/cs/allergyInt-reaction "שיבא - קודי תגובה לרגישות"
* #http://fhir.b-zion.health.gov.il/cs/allergyInt-reaction "בני ציון - קודי תגובה לרגישות"
//* #http://fhir.rambam.health.gov.il/cs/allergyInt-reaction "רמבם - קודי תגובה לרגישות"
* #http://fhir.shamir.health.gov.il/cs/allergyInt-reaction "שמיר - קודי תגובה לרגישות"
* #http://fhir.ziv.health.gov.il/cs/allergyInt-reaction "זיו - קודי תגובה לרגישות"
* #http://fhir.wolfson.health.gov.il/cs/allergyInt-reaction "וולפסון - קודי תגובה לרגישות"
* #http://fhir.tasmc.health.gov.il/cs/allergyInt-reaction "איכילוב - קודי תגובה לרגישות"
* #http://fhir.tzafon.health.gov.il/cs/allergyInt-reaction "פוריה - קודי תגובה לרגישות"


* #http://fhir.bmc.health.gov.il/cs/allergyInt-manifestation "ברזילי - קודי תגובה לרגישות"
* #http://fhir.gmc.health.gov.il/cs/allergyInt-manifestation "נהריה - קודי תגובה לרגישות"
* #http://fhir.hymc.health.gov.il/cs/allergyInt-manifestation "הלל יפה - קודי תגובה לרגישות"
//* #http://fhir.sheba.health.gov.il/cs/allergyInt-manifestation "שיבא - קודי תגובה לרגישות"
* #http://fhir.b-zion.health.gov.il/cs/allergyInt-manifestation "בני ציון - קודי תגובה לרגישות"
//* #http://fhir.rambam.health.gov.il/cs/allergyInt-manifestation "רמבם - קודי תגובה לרגישות"
* #http://fhir.shamir.health.gov.il/cs/allergyInt-manifestation "שמיר - קודי תגובה לרגישות"
* #http://fhir.ziv.health.gov.il/cs/allergyInt-manifestation "זיו - קודי תגובה לרגישות"
* #http://fhir.wolfson.health.gov.il/cs/allergyInt-manifestation "וולפסון - קודי תגובה לרגישות"
* #http://fhir.tasmc.health.gov.il/cs/allergyInt-manifestation "איכילוב - קודי תגובה לרגישות"
* #http://fhir.tzafon.health.gov.il/cs/allergyInt-manifestation "פוריה - קודי תגובה לרגישות"


// Condition
* #http://fhir.bmc.health.gov.il/identifier/cml-diagnosis-rowid "ברזילי - מזהה אבחנה בטבלת אבחנות"
* #http://fhir.gmc.health.gov.il/identifier/cml-diagnosis-rowid "נהריה - מזהה אבחנה בטבלת אבחנות"
* #http://fhir.hymc.health.gov.il/identifier/cml-diagnosis-rowid "הלל יפה - מזהה אבחנה בטבלת אבחנות"
//* #http://fhir.sheba.health.gov.il/identifier/cml-diagnosis-rowid "שיבא - מזהה אבחנה בטבלת אבחנות"
* #http://fhir.b-zion.health.gov.il/identifier/cml-diagnosis-rowid "בני ציון - מזהה אבחנה בטבלת אבחנות"
//* #http://fhir.rambam.health.gov.il/identifier/cml-diagnosis-rowid "רמבם - מזהה אבחנה בטבלת אבחנות"
* #http://fhir.shamir.health.gov.il/identifier/cml-diagnosis-rowid "שמיר - מזהה אבחנה בטבלת אבחנות"
* #http://fhir.ziv.health.gov.il/identifier/cml-diagnosis-rowid "זיו - מזהה אבחנה בטבלת אבחנות"
* #http://fhir.wolfson.health.gov.il/identifier/cml-diagnosis-rowid "וולפסון - מזהה אבחנה בטבלת אבחנות"
* #http://fhir.tasmc.health.gov.il/identifier/cml-diagnosis-rowid "איכילוב - מזהה אבחנה בטבלת אבחנות"
* #http://fhir.tzafon.health.gov.il/identifier/cml-diagnosis-rowid "פוריה - מזהה אבחנה בטבלת אבחנות"

* #http://fhir.bmc.health.gov.il/identifier/cml-diagnosis-code "ברזילי - קוד אבחנה-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-diagnosis-code "נהריה - קוד אבחנה-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-diagnosis-code "הלל יפה - קוד אבחנה-קמיליון"
//* #http://fhir.sheba.health.gov.il/identifier/cml-diagnosis-code "שיבא - קוד אבחנה-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-diagnosis-code "בני ציון - קוד אבחנה-קמיליון"
//* #http://fhir.rambam.health.gov.il/identifier/cml-diagnosis-code "רמבם - קוד אבחנה-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-diagnosis-code "שמיר - קוד אבחנה-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-diagnosis-code "זיו - קוד אבחנה-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-diagnosis-code "וולפסון - קוד אבחנה-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-diagnosis-code "איכילוב - קוד אבחנה-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-diagnosis-code "פוריה - קוד אבחנה-קמיליון"

* #http://fhir.b-zion.health.gov.il/cs/coview-imaging-unit-category "בני ציון-סוג הזמנה דימות"
* #http://fhir.ziv.health.gov.il/cs/coview-imaging-unit-category "זיו-סוג הזמנה דימות"
* #http://fhir.wolfson.health.gov.il/cs/coview-imaging-unit-category "וולפסון-סוג הזמנה דימות"
* #http://fhir.hymc.health.gov.il/cs/coview-imaging-unit-category "הלל יפה-סוג הזמנה דימות"
* #http://fhir.tasmc.health.gov.il/cs/coview-imaging-unit-category "איכילוב-סוג הזמנה דימות"
* #http://fhir.bmc.health.gov.il/cs/coview-imaging-unit-category "ברזילי-סוג הזמנה דימות"
* #http://fhir.gmc.health.gov.il/cs/coview-imaging-unit-category "נהריה-סוג הזמנה דימות"
//* #http://fhir.sheba.health.gov.il/cs/coview-imaging-unit-category "שיבא-סוג הזמנה דימות"
//* #http://fhir.rambam.health.gov.il/cs/coview-imaging-unit-category "רמבם-סוג הזמנה דימות"
* #http://fhir.shamir.health.gov.il/cs/coview-imaging-unit-category "שמיר-סוג הזמנה דימות"
* #http://fhir.tzafon.health.gov.il/cs/coview-imaging-unit-category "פוריה-סוג הזמנה דימות"

* #http://fhir.b-zion.health.gov.il/cs/img-doc-abnormal-flag "בני ציון-מזהה קודי תוצאה חריגה"
* #http://fhir.ziv.health.gov.il/cs/img-doc-abnormal-flag "זיו-מזהה קודי תוצאה חריגה"
* #http://fhir.wolfson.health.gov.il/cs/img-doc-abnormal-flag "וולפסון-מזהה קודי תוצאה חריגה"
* #http://fhir.hymc.health.gov.il/cs/img-doc-abnormal-flag "הלל יפה-מזהה קודי תוצאה חריגה"
* #http://fhir.tasmc.health.gov.il/cs/img-doc-abnormal-flag "איכילוב-מזהה קודי תוצאה חריגה"
* #http://fhir.bmc.health.gov.il/cs/img-doc-abnormal-flag "ברזילי-מזהה קודי תוצאה חריגה"
* #http://fhir.gmc.health.gov.il/cs/img-doc-abnormal-flag "נהריה-מזהה קודי תוצאה חריגה"
//* #http://fhir.sheba.health.gov.il/cs/img-doc-abnormal-flag "שיבא-מזהה קודי תוצאה חריגה"
//* #http://fhir.rambam.health.gov.il/cs/img-doc-abnormal-flag "רמבם-מזהה קודי תוצאה חריגה"
* #http://fhir.shamir.health.gov.il/cs/img-doc-abnormal-flag "שמיר-מזהה קודי תוצאה חריגה"
* #http://fhir.tzafon.health.gov.il/cs/img-doc-abnormal-flag "פוריה-מזהה קודי תוצאה חריגה"

* #http://fhir.b-zion.health.gov.il/identifier/nmr-img-doc "בני ציון-מזהה פענוח דימות"
* #http://fhir.ziv.health.gov.il/identifier/nmr-img-doc "זיו-מזהה פענוח דימות"
* #http://fhir.wolfson.health.gov.il/identifier/nmr-img-doc "וולפסון-מזהה פענוח דימות"
* #http://fhir.hymc.health.gov.il/identifier/nmr-img-doc "הלל יפה-מזהה פענוח דימות"
* #http://fhir.tasmc.health.gov.il/identifier/nmr-img-doc "איכילוב-מזהה פענוח דימות"
* #http://fhir.bmc.health.gov.il/identifier/nmr-img-doc "ברזילי-מזהה פענוח דימות"
* #http://fhir.gmc.health.gov.il/identifier/nmr-img-doc "נהריה-מזהה פענוח דימות"
//* #http://fhir.sheba.health.gov.il/identifier/nmr-img-doc "שיבא-מזהה פענוח דימות"
//* #http://fhir.rambam.health.gov.il/identifier/nmr-img-doc "רמבם-מזהה פענוח דימות"
* #http://fhir.shamir.health.gov.il/identifier/nmr-img-doc "שמיר-מזהה פענוח דימות"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-img-doc "פוריה-מזהה פענוח דימות"

* #http://fhir.b-zion.health.gov.il/identifier/nmr-img-doc-ver "בני ציון-מזהה פענוח דימות עם מספר גרסה"
* #http://fhir.ziv.health.gov.il/identifier/nmr-img-doc-ver "זיו-מזהה פענוח דימות עם מספר גרסה"
* #http://fhir.wolfson.health.gov.il/identifier/nmr-img-doc-ver "וולפסון-מזהה פענוח דימות עם מספר גרסה"
* #http://fhir.hymc.health.gov.il/identifier/nmr-img-doc-ver "הלל יפה-מזהה פענוח דימות עם מספר גרסה"
* #http://fhir.tasmc.health.gov.il/identifier/nmr-img-doc-ver "איכילוב-מזהה פענוח דימות עם מספר גרסה"
* #http://fhir.bmc.health.gov.il/identifier/nmr-img-doc-ver "ברזילי-מזהה פענוח דימות עם מספר גרסה"
* #http://fhir.gmc.health.gov.il/identifier/nmr-img-doc-ver "נהריה-מזהה פענוח דימות עם מספר גרסה"
//* #http://fhir.sheba.health.gov.il/identifier/nmr-img-doc-ver "שיבא-מזהה פענוח דימות עם מספר גרסה"
//* #http://fhir.rambam.health.gov.il/identifier/nmr-img-doc-ver "רמבם-מזהה פענוח דימות עם מספר גרסה"
* #http://fhir.shamir.health.gov.il/identifier/nmr-img-doc-ver "שמיר-מזהה פענוח דימות עם מספר גרסה"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-img-doc-ver "פוריה-מזהה פענוח דימות עם מספר גרסה"

* #http://fhir.b-zion.health.gov.il/identifier/nmr-img-order-number "בני ציון-הזמנה לשירות בדיד-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-img-order-number "זיו-הזמנה לשירות בדיד-נמר"
* #http://fhir.wolfson.health.gov.il/identifier/nmr-img-order-number "וולפסון-הזמנה לשירות בדיד-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-img-order-number "הלל יפה-הזמנה לשירות בדיד-נמר"
* #http://fhir.tasmc.health.gov.il/identifier/nmr-img-order-number "איכילוב-הזמנה לשירות בדיד-נמר"
* #http://fhir.bmc.health.gov.il/identifier/nmr-img-order-number "ברזילי-הזמנה לשירות בדיד-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-img-order-number "נהריה-הזמנה לשירות בדיד-נמר"
//* #http://fhir.sheba.health.gov.il/identifier/nmr-img-order-number "שיבא-הזמנה לשירות בדיד-נמר"
//* #http://fhir.rambam.health.gov.il/identifier/nmr-img-order-number "רמבם-הזמנה לשירות בדיד-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-img-order-number "שמיר-הזמנה לשירות בדיד-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-img-order-number "פוריה-הזמנה לשירות בדיד-נמר"

* #http://fhir.b-zion.health.gov.il/identifier/nmr-img-order-service "בני ציון-הזמנה לשירות בדיד-נמר"
* #http://fhir.ziv.health.gov.il/identifier/nmr-img-order-service "זיו-הזמנה לשירות בדיד-נמר"
* #http://fhir.wolfson.health.gov.il/identifier/nmr-img-order-service "בני ציון-הזמנה לשירות בדיד-נמר"
* #http://fhir.hymc.health.gov.il/identifier/nmr-img-order-service "בני ציון-הזמנה לשירות בדיד-נמר"
* #http://fhir.tasmc.health.gov.il/identifier/nmr-img-order-service "בני ציון-הזמנה לשירות בדיד-נמר"
* #http://fhir.bmc.health.gov.il/identifier/nmr-img-order-service "בני ציון-הזמנה לשירות בדיד-נמר"
* #http://fhir.gmc.health.gov.il/identifier/nmr-img-order-service "בני ציון-הזמנה לשירות בדיד-נמר"
//* #http://fhir.sheba.health.gov.il/identifier/nmr-img-order-service "בני ציון-הזמנה לשירות בדיד-נמר"
//* #http://fhir.rambam.health.gov.il/identifier/nmr-img-order-service "בני ציון-הזמנה לשירות בדיד-נמר"
* #http://fhir.shamir.health.gov.il/identifier/nmr-img-order-service "בני ציון-הזמנה לשירות בדיד-נמר"
* #http://fhir.tzafon.health.gov.il/identifier/nmr-img-order-service "בני ציון-הזמנה לשירות בדיד-נמר"

* #http://fhir.b-zion.health.gov.il/cs/nmr-img-service-group-code "בני ציון-ייצוג קודי לשירותי אב"
* #http://fhir.ziv.health.gov.il/cs/nmr-img-service-group-code "זיו-ייצוג קודי לשירותי אב"
* #http://fhir.wolfson.health.gov.il/cs/nmr-img-service-group-code "וולפסון-ייצוג קודי לשירותי אב"
* #http://fhir.hymc.health.gov.il/cs/nmr-img-service-group-code "הלל יפה-ייצוג קודי לשירותי אב"
* #http://fhir.tasmc.health.gov.il/cs/nmr-img-service-group-code "איכילוב-ייצוג קודי לשירותי אב"
* #http://fhir.bmc.health.gov.il/cs/nmr-img-service-group-code "ברזילי-ייצוג קודי לשירותי אב"
* #http://fhir.gmc.health.gov.il/cs/nmr-img-service-group-code "נהריה-ייצוג קודי לשירותי אב"
//* #http://fhir.sheba.health.gov.il/cs/nmr-img-service-group-code "שיבא-ייצוג קודי לשירותי אב"
//* #http://fhir.rambam.health.gov.il/cs/nmr-img-service-group-code "רמבם-ייצוג קודי לשירותי אב"
* #http://fhir.shamir.health.gov.il/cs/nmr-img-service-group-code "שמיר-ייצוג קודי לשירותי אב"
* #http://fhir.tzafon.health.gov.il/cs/nmr-img-service-group-code "פורייה-ייצוג קודי לשירותי אב"

// אומדנים

* #http://fhir.tzafon.health.gov.il/CodeSystem/cml-monitor-combo "פוריה- טבלת קומבו"
* #http://fhir.ziv.health.gov.il/CodeSystem/cml-monitor-combo "זיו - טבלת קומבו"
* #http://fhir.hymc.health.gov.il/CodeSystem/cml-monitor-combo "הלל יפה- טבלת קומבו"
* #http://fhir.bmc.health.gov.il/CodeSystem/cml-monitor-combo "ברזילי - טבלת קומבו"
* #http://fhir.b-zion.health.gov.il/CodeSystem/cml-monitor-combo "בני ציון - טבלת קומבו"
* #http://fhir.gmc.health.gov.il/CodeSystem/cml-monitor-combo "נהריה - טבלת קומבו"
* #http://fhir.wolfson.health.gov.il/CodeSystem/cml-monitor-combo "וולפסון - טבלת קומבו"
* #http://fhir.tasmc.health.gov.il/CodeSystem/cml-monitor-combo "איכילוב- טבל קומבו"
* #http://fhir.shamir.health.gov.il/CodeSystem/cml-monitor-combo "שמיר - טבלת קומבו"

* #http://fhir.tzafon.health.gov.il/identifier/cml-manual-monitor "פוריה- מזהה מדידה ידנית"
* #http://fhir.ziv.health.gov.il/identifier/cml-manual-monitor "זיו - מזהה מדידה ידנית"
* #http://fhir.hymc.health.gov.il/identifier/cml-manual-monitor "הלל יפה- מזהה מדידה ידנית"
* #http://fhir.bmc.health.gov.il/identifier/cml-manual-monitor "ברזילי - מזהה מדידה ידנית"
* #http://fhir.b-zion.health.gov.il/identifier/cml-manual-monitor "בני ציון - מזהה מדידה ידנית"
* #http://fhir.gmc.health.gov.il/identifier/cml-manual-monitor "נהריה - מזהה מדידה ידנית"
* #http://fhir.wolfson.health.gov.il/identifier/cml-manual-monitor "וולפסון - מזהה מדידה ידנית"
* #http://fhir.tasmc.health.gov.il/identifier/cml-manual-monitor "איכילוב - מזהה מדידה ידנית"
* #http://fhir.shamir.health.gov.il/identifier/cml-manual-monitor "שמיר - מזהה מדידה ידנית"

* #http://fhir.tzafon.health.gov.il/identifier/cml-device-monitor "פוריה- מזהה מדידה ממכשיר"
* #http://fhir.ziv.health.gov.il/identifier/cml-device-monitor "זיו - מזהה מדידה ממכשיר"
* #http://fhir.hymc.health.gov.il/identifier/cml-device-monitor "הלל יפה- מזהה מדידה ממכשיר"
* #http://fhir.bmc.health.gov.il/identifier/cml-device-monitor "ברזילי - מזהה מדידה ממכשיר"
* #http://fhir.b-zion.health.gov.il/identifier/cml-device-monitor "בני ציון - מזהה מדידה ממכשיר"
* #http://fhir.gmc.health.gov.il/identifier/cml-device-monitor "נהריה - מזהה מדידה ממכשיר"
* #http://fhir.wolfson.health.gov.il/identifier/cml-device-monitor "וולפסון - מזהה מדידה ממכשיר"
* #http://fhir.tasmc.health.gov.il/identifier/cml-device-monitor "איכילוב - מזהה מדידה ממכשיר"
* #http://fhir.shamir.health.gov.il/identifier/cml-device-monitor "שמיר - מזהה מדידה ממכשיר"

* #http://fhir.tzafon.health.gov.il/identifier/cml-devices "פוריה- מזהה מכשיר"
* #http://fhir.ziv.health.gov.il/identifier/cml-devices "זיו - מזהה מכשיר"
* #http://fhir.hymc.health.gov.il/identifier/cml-devices "הלל יפה- מזהה מכשיר"
* #http://fhir.bmc.health.gov.il/identifier/cml-devices "ברזילי - מזהה מכשיר"
* #http://fhir.b-zion.health.gov.il/identifier/cml-devices "בני ציון - מזהה מכשיר"
* #http://fhir.gmc.health.gov.il/identifier/cml-devices "נהריה - מזהה מכשיר"
* #http://fhir.wolfson.health.gov.il/identifier/cml-devices "וולפסון - מזהה מכשיר"
* #http://fhir.tasmc.health.gov.il/identifier/cml-devices "איכילוב - מזהה מכשיר"
* #http://fhir.shamir.health.gov.il/identifier/cml-devices "שמיר - מזהה מכשיר"

//תרופות

* #http://fhir.bmc.health.gov.il/identifier/cml-internal-drug-code "ברזילי - קוד תרופה פנימי-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-internal-drug-code "נהריה - מקוד תרופה פנימי-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-internal-drug-code "הלל יפה - קוד תרופה פנימי-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-internal-drug-code "בני ציון - קוד תרופה פנימי-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-internal-drug-code "שמיר - קוד תרופה פנימי-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-internal-drug-code "זיו - קוד תרופה פנימי-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-internal-drug-code "וולפסון - קוד תרופה פנימי-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-internal-drug-code "איכילוב - קוד תרופה פנימי-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-internal-drug-code "פוריה - קוד תרופה פנימי-קמיליון"

* #http://fhir.bmc.health.gov.il/identifier/cml-external-drug-code "ברזילי - קוד תרופה חיצוני-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-external-drug-code "נהריה - מקוד תרופה חיצוני-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-external-drug-code "הלל יפה - קוד תרופה חיצוני-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-external-drug-code "בני ציון - קוד תרופה חיצוני-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-external-drug-code "שמיר - קוד תרופה חיצוני-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-external-drug-code "זיו - קוד תרופה חיצוני-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-external-drug-code "וולפסון - קוד תרופה חיצוני-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-external-drug-code "איכילוב - קוד תרופה חיצוני-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-external-drug-code "פוריה - קוד תרופה חיצוני-קמיליון"

* #http://fhir.bmc.health.gov.il/identifier/cml-med-route-code "ברזילי - קוד אופן מתן תרופה-קמיליון"
* #http://fhir.gmc.health.gov.il/identifier/cml-med-route-code "נהריה - קוד אופן מתן תרופה-קמיליון"
* #http://fhir.hymc.health.gov.il/identifier/cml-med-route-code "הלל יפה - קוד אופן מתן תרופה-קמיליון"
* #http://fhir.b-zion.health.gov.il/identifier/cml-med-route-code "בני ציון - קוד אופן מתן תרופה-קמיליון"
* #http://fhir.shamir.health.gov.il/identifier/cml-med-route-code "שמיר - קוד אופן מתן תרופה-קמיליון"
* #http://fhir.ziv.health.gov.il/identifier/cml-med-route-code "זיו - קוד אופן מתן תרופה-קמיליון"
* #http://fhir.wolfson.health.gov.il/identifier/cml-med-route-code "וולפסון - קוד אופן מתן תרופה-קמיליון"
* #http://fhir.tasmc.health.gov.il/identifier/cml-med-route-code "איכילוב - קוד אופן מתן תרופה-קמיליון"
* #http://fhir.tzafon.health.gov.il/identifier/cml-med-route-code "פוריה - קוד אופן מתן תרופה-קמיליון"